trigger: none

pool: infra

variables:
  workDir: '$(System.DefaultWorkingDirectory)/environments/dev'

stages:
- stage: TerraformInit
  displayName: Terraform Init Stage
  jobs:
  - job: TerraformInitJob
    displayName: Terraform Init Job
    steps:
    # Terraform init only
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workDir)
        backendServiceArm: 'Azure subscription 1(56de03ab-1570-40b1-bd13-5a9ca5b1e106)'
        backendAzureRmStorageAccountName: 'infrastoregeal'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'
